import Image from 'next/image'
import Head from 'next/head'

export default function Home() {
  return (
    <div className="container py-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-16 justify-center align-center items-center">
        <div className="section-1 flex flex-1 mx-8 min-h-screen w-full text-green-800 bg-gray-300">Section-A
        </div>

        <div className="section-1 flex flex-1 mx-8 min-h-screen w-full text-green-800 bg-gray-400">Section-B
        </div>

        <div className="section-1 flex flex-1 mx-8 min-h-screen w-full text-green-800 bg-gray-300">Section-A
        </div>

        <div className="section-1 flex flex-1 mx-8 min-h-screen w-full text-green-800 bg-gray-400">Section-B
        </div>
      </main>
    </div>
  )
}
