import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <main className="">
      <div className="section-1 col-start-1 col-end-13 row-span-1 flex flex-row flex-wrap">
      </div>
    </main>
    </div>
  )
}
